- name: functions
  hosts: runner
  #connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
    status: needs_restart
    enabled: false
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"

  - name: convert to uppercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"

  - name: Example 1 - Simple ternary
    debug:
      msg: "{{ (status == 'needs_restart') | ternary('restart service', 'continue service') }}"

  - name: Example 2 - Ternary with null handling
    debug:
      msg: "{{ enabled | ternary('no shutdown', 'shutdown', omit) }}"

  - name: Read YAML file and convert to JSON
    set_fact:
      yaml_data: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: Save JSON output to file
    copy:
      content: "{{ yaml_data | to_nice_json }}"
      dest: "./data.json"

  - name: Show JSON output
    debug:
      msg: "{{ yaml_data | to_nice_json }}"

  - name: Print environment variable
    ansible.builtin.command: echo $HOME